management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,heapdump,prometheus"
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3307}/repaymentplan
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.jdbc.Driver