management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,heapdump,prometheus"
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/repaymentplan
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver