management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,heapdump,prometheus"
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
