spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3305/repaymentplan
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,heapdump,prometheus"
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
